title: John Klockenkemper # your name (or website title) here
logo: "/images/me.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Hi! I'm John Klockenkemper. I'm a long term IT professional with leadership experience and a passion for automation, devops, and securtity,
  <br><br>
  If you are interested in getting in touch with me, please reach out to me on linkedin and we can take it from there.  
  <br><br>
  <a href="https://www.linkedin.com/in/johntklockenkemper/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
